### ISSUE TITLE
Calculation accuracy for drop frame timecode

### ISSUE THREAD

**Issue by ertee** [x42/libtimecode#5]
Been trying to track down an issue that is popping up when doing conversions between a timecode and a frame number using a framerate of 29.97DF.

Take 08:33:25;02 for example:

Converted to a frame number at 29.97DF, libtimecode returns 923227.  The correct value is 923228.
When the result of 923227 is sent back to libtimecode to be converted to a time, it returns 08:33:25;01.

Presumably using libtimecode to go to a frame number and back again should always yield the same result consistently, so something is getting switched in the math somewhere.  Could this be due to rounding?

**Comment by x42** [comment]
Thanks for the heads up.  It turned out to be a rounding issue.
Under the hood `timecode_to_framenumber` uses `timecode_to_sample` with `sample-rate == fps_d`

Mathematically  `frameNumber * samplerate / fps_d  == frameNumber`  but on a PC that's not true for large numbers (even using double floating point precision).
The solution was to use `frameNumber * (samplerate / fps_d)`
